import { Inter } from "next/font/google";
import "../globals.css";
import HeaderAdmin from "@/components/ui/HeaderAdmin";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {

    return (

        <div className="flex">
            <HeaderAdmin />
            <div className="mx-auto">{children}</div>
        </div>
    );
}
